mysite/blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.home, name='home'), # пустой адрес соответствует странице home
	url(r'^blog/$', views.blog, name='blog'),
    url(r'^blog/(?P<post_id>[0-9]+)/$', views.post, name='post') # адрес с цифрой соответствует посту
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls')), # Отправляем смотерть url-ы в blog
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model): # модель поста с автором, датой, названием и текстом
    author = models.ForeignKey('auth.User')
    pub_date = models.DateTimeField( default=timezone.now )
    title = models.CharField(max_length=200)
    text = models.TextField()

    def publish(self):
        self.pub_date = timezone.now()
        self.save()
        
    def __str__(self):
        return self.title
        
class Comment(models.Model): #Модель комментария с постом, к которому он идет, текстом и датой
    rel_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    pub_date = models.DateTimeField( default=timezone.now )
    
    def publish(self):
        self.pub_date = timezone.now()
        self.save()
        
    def __str__(self):
        return self.rel_post.title + ' ' + self.text

mysite/blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text', 'text',) # недоделанная форма для комментария

mysite/blog/views.py
from django.shortcuts import get_object_or_404,render
from .models import Post, Comment
from .forms import CommentForm

def home(request): # Рендеринг домашней страницы
    return render(request, 'pages/home.html')
    
def blog(request):
    posts = Post.objects.order_by('-pub_date')  # рендеринг страницы с постами
    return render(request, 'pages/posts.html', {'posts': posts} )
 
def post(request, post_id): # рендеринг страницы с каждым отдельным постом
    post = get_object_or_404(Post, pk=post_id)
    comments = Comment.objects.filter(rel_post = post_id) # и комментариями, которые пока что можно писать только из админки
    form = CommentForm() 
    return render(request, 'pages/post_page.html', {'post': post, 'comments': comments, 'form': form})

mysite/blog/templates/pages/home.html
<a href="{% url 'blog:blog' %}">Go to Blog</a>

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

mysite/blog/templates/pages/post_page.html
<a href="/blog">Go back</a>


<h1>{{ post.title }}</h1> <!-- вывод названия, текста, автора и дату поста из бд в шаблон-->
<h2>{{post.text}}</h2>
<h3>{{ post.author }}</h3>
<h4>{{ post.pub_date }}</h4>

<h2>Comments</h2>

<form>
    <label for="your_comment">Your comment: </label>
    <input id="your_comment" type="text" name="your_comment" value="{{ current_name }}">
    <input type="submit" value="OK">
</form> <!-- форма для написания комментария, которая пока что ничего не делает -->

<ul>
{% for comment in comments %}
<li>{{ comment.text }} - {{ comment.pub_date }}</a></li>
{% endfor %}
</ul> <!-- комментарии в виде списка  -->

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

mysite/blog/templates/pages/posts.html
<a href="/">Go Home</a>
<ul>
{% for post in posts %}
<li><a href="{% url 'blog:post' post.id %}">{{ post }} ({{post.pub_date}} by {{ post.author}} )</a></li>
<p>{{post.text}}</p>
{% endfor %}
</ul>
<!-- ^^^ вывод постов в виде списка -->
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />